name: food_delivery_app
description: A modern food delivery application using Flutter and Supabase.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.8.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  state_notifier: ^1.0.0

  # Routing
  go_router: ^16.3.0

  # UI components
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  lottie: ^3.1.0

  # Data and networking
  supabase_flutter: ^2.10.3
  dio: ^5.3.2

  # Local storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location services
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Notifications
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

  # Firebase
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  firebase_analytics: ^12.0.2
  firebase_performance: ^0.11.0
  firebase_crashlytics: ^5.0.3

  # Payments
  # PayFast integration for South African payment processing
  webview_flutter: ^4.10.0
  connectivity_plus: ^7.0.0
  package_info_plus: ^8.1.2
  flutter_secure_storage: ^9.2.2

  # Images and media
  image_picker: ^1.2.0
  path_provider: ^2.1.1

  # Security
  crypto: ^3.0.3
  json_annotation: ^4.9.0

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Social Authentication
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.2

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  collection: ^1.17.2
  url_launcher: ^6.2.2

  # Charts and Analytics
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  very_good_analysis: ^10.0.0

  # Testing
  mocktail: ^1.0.0

  # Code generation
  build_runner: ^2.4.13
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/branding/
    - assets/animations/
    - .env

 # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages