name: food_delivery_app
description: A modern food delivery application using Flutter and Supabase.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.8.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.9
  state_notifier: ^1.0.0

  # Routing
  go_router: ^12.1.3

  # UI components
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  lottie: ^3.1.0

  # Data and networking
  supabase_flutter: ^2.3.0
  dio: ^5.3.2
  http: ^1.1.0

  # Local storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # Location services
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2

  # Firebase
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.0
  firebase_analytics: ^10.7.0
  firebase_performance: ^0.9.3
  firebase_crashlytics: ^3.4.0

  # Payments (currently using cash only)
  # Payment gateway integration can be added later

  # Images and media
  image_picker: ^1.0.4
  # image_cropper: ^5.0.0  # Temporarily disabled due to compatibility issue
  path_provider: ^2.1.1

  # Security
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  http_certificate_pinning: ^3.0.1
  local_auth: ^2.2.0
  json_annotation: ^4.9.0

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Social Authentication
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^6.1.2

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  collection: ^1.17.2
  url_launcher: ^6.2.2

  # Charts and Analytics
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  very_good_analysis: ^5.1.0

  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  json_annotation: ^4.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/branding/
    - assets/animations/
    - .env

 # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages